### PR TITLE
adding some styles

### PR DESCRIPTION
**Pull request by vermad843**
here I changed some styles and some other things hope you like it. I learn all this from you thank you for everything.
please give me more tips on how to get better at this.thankyou!!!!!

### CODE REVIEW

**Comment by w3cj** [comment]
Thanks for the contribution, but you accidently commited your node_modules!
Also, it looks like you're using an auto formatter. This has changed the formatting of all files instead of just the files you have added / edited.

Please fix these things and re-submit.

**Comment by w3cj** [comment]
Also, I see that you updated the README file.

Please submit a pull request with only the necessary changes.

**Comment by vermad843** [comment]
ohk i will thankyou

**Comment by vermad843** [comment]
ohk.

**Comment by vermad843** [comment]
Cj i have some questions  related to unplash API and heroku deployment can you please tell me where i should ask these questions.

**Comment by vermad843** [comment]
hey CJ can you please check the meower pull request

**Pull request closed without merging**
