### PR TITLE
adding styles

### PR DESCRIPTION
**Pull request by vermad843**
here I added some styles and followed your instructions.thankyou for explaining things so nicely to me.
please let me know if there is any other problem with this.

### CODE REVIEW

**Comment by vermad843** [comment]
hey Cj can you please check this pull request.

**Comment by vermad843** [comment]
hey Cj are you there!!!

**Comment by vermad843** [comment]
hey CJ can you please check the pull request.

**Comment by w3cj** [comment]
I appreciate the style changes, but I want to keep the site looking the same way as in the video.

**Pull request closed without merging**
